//
//  AWSCompetition.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers
class AWSCompetition: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _categoryTypeId: NSNumber?
    var _competitionId: String?
    var _competitionIsActive: NSNumber?
    var _competitionTypeId: NSNumber?
    var _expireDate: String?
    var _firstEntryCommentCount: NSNumber?
    var _firstEntryCaption: String?
    var _firstEntryCompetitionEntryId: String?
    var _firstEntryMediaId: String?
    var _firstEntryUsername: String?
    var _firstEntryUserRankId: NSNumber?
    var _firstEntryUserId: String?
    var _firstEntryVoteCount: NSNumber?
    var _isFeatured: NSNumber?
    var _isFeaturedCategoryTypeId: String?
    var _secondEntryCommentCount: NSNumber?
    var _secondEntryCaption: String?
    var _secondEntryCompetitionEntryId: String?
    var _secondEntryMediaId: String?
    var _secondEntryUsername: String?
    var _secondEntryUserRankId: NSNumber?
    var _secondEntryUserId: String?
    var _secondEntryVoteCount: NSNumber?
    var _startDate: String?
    var _timeExtended: NSNumber?
    var _winnerUserId: String?
    
    class func dynamoDBTableName() -> String {

        return "AWS_Competition"
    }
    
    class func hashKeyAttribute() -> String {

        return "_competitionId"
    }
    
    class func rangeKeyAttribute() -> String {
        
        return "_startDate"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
                "_categoryTypeId" : "categoryTypeId",
                "_competitionId" : "competitionId",
                "_competitionIsActive" : "competitionIsActive",
                "_competitionTypeId" : "competitionTypeId",
                "_expireDate" : "expireDate",
                "_firstEntryCommentCount" : "firstEntryCommentCount",
                "_firstEntryCaption" : "firstEntryCaption",
                "_firstEntryCompetitionEntryId" : "firstEntryCompetitionEntryId",
                "_firstEntryMediaId" : "firstEntryMediaId",
                "_firstEntryUsername" : "firstEntryUsername",
                "_firstEntryUserRankId" : "firstEntryUserRankId",
                "_firstEntryUserId" : "firstEntryUserId",
                "_firstEntryVoteCount" : "firstEntryVoteCount",
                "_isFeatured" : "isFeatured",
                "_isFeaturedCategoryTypeId" : "isFeaturedCategoryTypeId",
                "_secondEntryCommentCount" : "secondEntryCommentCount",
                "_secondEntryCaption" : "secondEntryCaption",
                "_secondEntryCompetitionEntryId" : "secondEntryCompetitionEntryId",
                "_secondEntryMediaId" : "secondEntryMediaId",
                "_secondEntryUsername" : "secondEntryUsername",
                "_secondEntryUserRankId" : "secondEntryUserRankId",
                "_secondEntryUserId" : "secondEntryUserId",
                "_secondEntryVoteCount" : "secondEntryVoteCount",
                "_startDate" : "startDate",
                "_timeExtended" : "timeExtended",
                "_winnerUserId" : "winnerUserId",
        ]
    }
}
