//
//  AWSComment.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers
class AWSComment: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _competitionEntryId: String?
    var _createDate: String?
    var _commentId: String?
    var _commentText: String?
    var _userPoolUserId: String?
    var _username: String?
    
    class func dynamoDBTableName() -> String {

        return "versus-mobilehub-387870640-AWS_Comment"
    }
    
    class func hashKeyAttribute() -> String {

        return "_competitionEntryId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_createDate"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_competitionEntryId" : "competitionEntryId",
               "_createDate" : "createDate",
               "_commentId" : "commentId",
               "_commentText" : "commentText",
               "_userPoolUserId" : "userPoolUserId",
               "_username" : "username",
        ]
    }
}
