//
//  AWSCompetition.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers
class AWSCompetition: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _categoryTypeId: NSNumber?
    var _competitionId: String?
    var _competitionIsActive: NSNumber?
    var _competitionTypeId: NSNumber?
    var _expireDate: String?
    var _firstCompetitorCommentCount: NSNumber?
    var _firstCompetitorCaption: String?
    var _firstCompetitorEntryId: String?
    var _firstCompetitorMediaId: String?
    var _firstCompetitorUsername: String?
    var _firstCompetitorUserRankId: NSNumber?
    var _firstCompetitorUserId: String?
    var _firstCompetitorVoteCount: NSNumber?
    var _isFeatured: NSNumber?
    var _isFeaturedCategoryTypeId: String?
    var _secondCompetitorCommentCount: NSNumber?
    var _secondCompetitorCaption: String?
    var _secondCompetitorEntryId: String?
    var _secondCompetitorMediaId: String?
    var _secondCompetitorUsername: String?
    var _secondCompetitorUserRankId: NSNumber?
    var _secondCompetitorUserId: String?
    var _secondCompetitorVoteCount: NSNumber?
    var _startDate: String?
    var _timeExtended: NSNumber?
    var _winnerUserId: String?
    
    class func dynamoDBTableName() -> String {

        return "AWS_Competition"
    }
    
    class func hashKeyAttribute() -> String {

        return "_competitionId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
                "_categoryTypeId" : "categoryTypeId",
                "_competitionId" : "competitionId",
                "_competitionIsActive" : "competitionIsActive",
                "_competitionTypeId" : "competitionTypeId",
                "_expireDate" : "expireDate",
                "_firstCompetitorCommentCount" : "firstCompetitorCommentCount",
                "_firstCompetitorCaption" : "firstCompetitorCaption",
                "_firstCompetitorEntryId" : "firstCompetitorEntryId",
                "_firstCompetitorMediaId" : "firstCompetitorMediaId",
                "_firstCompetitorUsername" : "firstCompetitorUsername",
                "_firstCompetitorUserRankId" : "firstCompetitorUserRankId",
                "_firstCompetitorUserId" : "firstCompetitorUserId",
                "_firstCompetitorVoteCount" : "firstCompetitorVoteCount",
                "_isFeatured" : "isFeatured",
                "_isFeaturedCategoryTypeId" : "isFeaturedCategoryTypeId",
                "_secondCompetitorCommentCount" : "secondCompetitorCommentCount",
                "_secondCompetitorCaption" : "secondCompetitorCaption",
                "_secondCompetitorEntryId" : "secondCompetitorEntryId",
                "_secondCompetitorMediaId" : "secondCompetitorMediaId",
                "_secondCompetitorUsername" : "secondCompetitorUsername",
                "_secondCompetitorUserRankId" : "secondCompetitorUserRankId",
                "_secondCompetitorUserId" : "secondCompetitorUserId",
                "_secondCompetitorVoteCount" : "secondCompetitorVoteCount",
                "_startDate" : "startDate",
                "_timeExtended" : "timeExtended",
                "_winnerUserId" : "winnerUserId",
        ]
    }
}
