//
//  AWSCompetitionEntry.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.20
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers
class AWSCompetitionEntry: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _id: String?
    var _caption: String?
    var _categoryId: NSNumber?
    var _competitionTypeId: NSNumber?
    var _createDate: String?
    var _imageId: String?
    var _imageSmallId: String?
    var _isFeatured: NSNumber?
    var _matchDate: String?
    var _userPoolUserId: String?
    var _userRankId: NSNumber?
    var _username: String?
    var _videoId: String?
    var _videoPreviewImageId: String?
    var _videoPreviewImageSmallId: String?
    
    class func dynamoDBTableName() -> String {

        return "versus-mobilehub-387870640-AWS_CompetitionEntry"
    }
    
    class func hashKeyAttribute() -> String {

        return "_id"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_id" : "id",
               "_caption" : "caption",
               "_categoryId" : "categoryId",
               "_competitionTypeId" : "competitionTypeId",
               "_createDate" : "createDate",
               "_imageId" : "imageId",
               "_imageSmallId" : "imageSmallId",
               "_isFeatured" : "isFeatured",
               "_matchDate" : "matchDate",
               "_userPoolUserId" : "userPoolUserId",
               "_userRankId" : "userRankId",
               "_username" : "username",
               "_videoId" : "videoId",
               "_videoPreviewImageId" : "videoPreviewImageId",
               "_videoPreviewImageSmallId" : "videoPreviewImageSmallId",
        ]
    }
}
