//
//  AWSCompetitionEntry.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers
class AWSCompetitionEntry: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _awaitingMatch: NSNumber?
    var _caption: String?
    var _categoryTypeId: NSNumber?
    var _competitionEntryId: String?
    var _compTypeIdCatTypeIdRankIdMatched: String?
    var _competitionTypeId: NSNumber?
    var _createDate: String?
    var _displayName: String?
    var _isFeatured: NSNumber?
    var _mediaId: String?
    var _rankId: NSNumber?
    var _userId: String?
    var _username: String?
    
    class func dynamoDBTableName() -> String {

        return "AWS_CompetitionEntry"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_awaitingMatch" : "awaitingMatch",
               "_caption" : "caption",
               "_categoryTypeId" : "categoryTypeId",
               "_competitionEntryId" : "competitionEntryId",
               "_compTypeIdCatTypeIdRankIdMatched" : "compTypeIdCatTypeIdRankIdMatched",
               "_competitionTypeId" : "competitionTypeId",
               "_createDate" : "createDate",
               "_displayName" : "displayName",
               "_isFeatured" : "isFeatured",
               "_mediaId" : "mediaId",
               "_rankId" : "rankId",
               "_userId" : "userId",
               "_username" : "username",
        ]
    }
}
