//
//  AWSFollower.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers
class AWSFollower: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _createDate: String?
    var _displayName: String?
    var _followerUserId: String?
    var _searchDisplayName: String?
    var _searchUsername: String?
    var _username: String?
    var _userId: String?
    
    class func dynamoDBTableName() -> String {

        return "AWS_Follower"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {
        
        return "_createDate"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
                "_createDate" : "createDate",
                "_displayName" : "displayName",
                "_followerUserId" : "followerUserId",
                "_searchDisplayName" : "searchDisplayName",
                "_searchUsername" : "searchUsername",
                "_username" : "username",
                "_userId" : "userId",
        ]
    }
}
