//
//  AWSLeaderboard.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers
class AWSLeaderboard: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _leaderboardTypeId: NSNumber?
    var _isActive: NSNumber?
    var _name: String?
    var _numberOfResults: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "AWS_Leaderboard"
    }
    
    class func hashKeyAttribute() -> String {

        return "_leaderboardTypeId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_leaderboardTypeId" : "leaderboardTypeId",
               "_isActive" : "isActive",
               "_name" : "name",
               "_numberOfResults" : "numberOfResults",
        ]
    }
}
