//
//  AWSNotification.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers
class AWSNotification: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _notifyUserPoolUserId: String?
    var _createDate: String?
    var _notificationInfo: [String: String]?
    var _notificationTypeId: NSNumber?
    var _wasViewed: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "versus-mobilehub-387870640-AWS_Notification"
    }
    
    class func hashKeyAttribute() -> String {

        return "_notifyUserPoolUserId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_createDate"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_notifyUserPoolUserId" : "notifyUserPoolUserId",
               "_createDate" : "createDate",
               "_notificationInfo" : "notificationInfo",
               "_notificationTypeId" : "notificationTypeId",
               "_wasViewed" : "wasViewed",
        ]
    }
}
