//
//  AWSUser.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers
class AWSUser: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _bio: String?
    var _createDate: String?
    var _directMessageConversationIds: [String: String]?
    var _displayName: String?
    var _followedUserCount: NSNumber?
    var _followerCount: NSNumber?
    var _isFeatured: NSNumber?
    var _rankId: NSNumber?
    var _searchDisplayName: String?
    var _searchUsername: String?
    var _totalTimesVoted: NSNumber?
    var _totalWins: NSNumber?
    var _userId: String?
    var _username: String?
    
    class func dynamoDBTableName() -> String {

        return "AWS_User"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
                "_bio" : "bio",
                "_createDate" : "createDate",
                "_directMessageConversationIds" : "directMessageConversationIds",
                "_displayName" : "displayName",
                "_followedUserCount" : "followedUserCount",
                "_followerCount" : "followerCount",
                "_isFeatured" : "isFeatured",
                "_rankId" : "rankId",
                "_searchDisplayName" : "searchDisplayName",
                "_searchUsername" : "searchUsername",
                "_totalTimesVoted" : "totalTimesVoted",
                "_totalWins" : "totalWins",
                "_userId" : "userId",
                "_username" : "username",
        ]
    }
}
