//
//  AWSVote.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers
class AWSVote: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _competitionId: String?
    var _competitionIdUserId: String?
    var _competitionEntryId: String?
    var _competitor: String?
    
    class func dynamoDBTableName() -> String {

        return "AWS_Vote"
    }
    
    class func hashKeyAttribute() -> String {

        return "_competitionIdUserId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_competitionId" : "competitionId",
               "_competitionIdUserId" : "competitionIdUserId",
               "_competitionEntryId" : "competitionEntryId",
               "_competitor" : "competitor",
        ]
    }
}
