//
//  AWSWeeklyLeader.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers
class AWSWeeklyLeader: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _username: String?
    var _votes: NSNumber?
    var _weekYear: NSNumber?
    var _weekYearUserId: String?
    var _wins: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "AWS_WeeklyLeader"
    }
    
    class func hashKeyAttribute() -> String {

        return "_weekYearUserId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_wins"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
                "_userId" : "_userId",
                "_username" : "username",
                "_votes" : "votes",
                "_weekYear" : "weekYear",
                "_weekYearUserId" : "weekYearUserId",
                "_wins" : "wins",
        ]
    }
}
