//
//  User.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers
class User: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _username: String?
    var _bio: String?
    var _createDate: String?
    var _profileImageBackgroundId: String?
    var _profileImageId: String?
    var _profileImageSmallId: String?
    var _rankId: NSNumber?
    var _updateDate: String?
    var _userPoolUserId: String?
    var _votes: NSNumber?
    var _wins: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "versus-mobilehub-387870640-User"
    }
    
    class func hashKeyAttribute() -> String {

        return "_username"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_username" : "username",
               "_bio" : "bio",
               "_createDate" : "createDate",
               "_profileImageBackgroundId" : "profileImageBackgroundId",
               "_profileImageId" : "profileImageId",
               "_profileImageSmallId" : "profileImageSmallId",
               "_rankId" : "rankId",
               "_updateDate" : "updateDate",
               "_userPoolUserId" : "userPoolUserId",
               "_votes" : "votes",
               "_wins" : "wins",
        ]
    }
}
