# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Versus' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Versus
  pod 'AWSS3'
  pod 'Toast-Swift'
  pod 'SwiftyCam'
end
