# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Versus' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Versus
  pod 'AWSMobileClient', '~> 2.6.13'
  pod 'AWSUserPoolsSignIn', '~> 2.6.13'
  pod 'AWSDynamoDB', '~> 2.6.13'
  pod 'AWSS3', '~> 2.6.13'
  pod 'AWSCognito', '~> 2.6.13'
  pod 'Toast-Swift', '~> 3.0.1'
  pod 'SwiftyCam'
end
